### ISSUE TITLE
Can't install it from extensions.gnome.org

### ISSUE THREAD

**Issue by Paviluf** [windsorschmidt/disable-workspace-switcher-popup#20]
Hello,

The installation doesn't seem to work from https://extensions.gnome.org/extension/959/disable-workspace-switcher-popup/. I only can install it manually as explained in README.md and with a logout/login (restarting gnome-shell is not enough) to make the extension appear in gnome-tweak-tool to enable it.

Do you think you can fix it ?

Thank you !

**Comment by eevleevs** [comment]
Same here, Ubuntu 16.04.

**Comment by zAMLz** [comment]
The issue arises because the current gnome-shell version "3.22.3" is not in the list of shell version in the metadata.json file. You can add "3.22.3" yourself which is what I did. I have tested it on my Antergos setup and have not run into any issues. I have also setup a pull request as well. #22

**Comment by windsorschmidt** [comment]
I finally realized that I was having trouble uploading to extensions.gnome.org because I had two very similarly named accounts there, and I was using the wrong one! Should be up to date now.

**Comment by Paviluf** [comment]
Seem to work now. Thanks !
