### ISSUE TITLE
Possible to disable brightness/volume change OSD popup

### ISSUE THREAD

**Issue by Mancooo** [windsorschmidt/disable-workspace-switcher-popup#23]
Hi,

Is it possible to also disable the popup OSD when changing the brightness/volume or mute volume in Gnome with your extension? I am on Gnome 3.22.2 (Fedora 25) and I find those popups very annoying.

Maybe an option to choose to enable/disable workspace popup, enable/disable brightness change and enable/disable volume change including volume mute/unmute?

Love your extension btw. Would be awesome if the above feature can be implemented. I can test it if needed.

**Comment by windsorschmidt** [comment]
Apologies for the late reply. I'm not using Gnome on a regular basis any more. While patches are welcome, I will not be adding this or any new features.
