### ISSUE TITLE
gnome-shell 3.25.4 does not open tweaks tool with this extension

### ISSUE THREAD

**Issue by vans163** [windsorschmidt/disable-workspace-switcher-popup#26]
If this extension is in your extensions folder, tweaks tool fails to open.

**Comment by windsorschmidt** [comment]
Odd minor versions of gnome-shell (e.g. 3.25.x) are not considered stable releases. It's working fine for me in 3.24. If you have details about the failure, or if it's still a problem using a stable release of gnome-shell, feel free to open another issue. Thanks!

![ss](https://user-images.githubusercontent.com/1273851/29146325-710eaadc-7d15-11e7-90e9-284b43337b54.png)
