### ISSUE TITLE
Disable the animation, too?

### ISSUE THREAD

**Issue by searene** [windsorschmidt/disable-workspace-switcher-popup#28]
Hi,

I installed this amazing plugin today, and it worked, thanks!

Just one more thing, is it possible to disable the switching animation too? For someone who constantly switches between different workspaces, the switching animation is pretty annoying.

**Comment by windsorschmidt** [comment]
Hi, sorry for such a late reply. This plugin disables the overlay displayed while switching work-spaces. What animation are you referring to here?

**Comment by Jeansen** [comment]
Maybe this one? https://askubuntu.com/questions/654976/gnome-3-14-how-to-disable-window-effects

**Comment by windsorschmidt** [comment]
I agree it's annoying, but no, it is not possible to disable the window switching animation with this plugin. The solution in https://github.com/windsorschmidt/disable-workspace-switcher-popup/issues/28#issuecomment-393998534 may work for you.
