### ISSUE TITLE
No dynamic workspaces when this extension is active

### ISSUE THREAD

**Issue by Jeansen** [windsorschmidt/disable-workspace-switcher-popup#30]
I am using GNOME 3.28.2. This extension successfully disables the popup. However, it breaks the dynamic workspaces in GNOME. I can only use 2 workpsaces.

**Comment by Solarinass** [comment]
I am experiencing the same issue on GNOME 3.26.2 on OpenSUSE leap 15.0. I only get 2 workspaces and GNOME fails to auto create another one. By restarting the GNOME Shell I am able to create a new workspace automatically but I need to do that each time I want to create a workspace.

I've tried turning off all my other extensions to see if there was maybe a conflict between this extension and one of them but the issue persisted. It seems like only way to get dynamic workspaces to work again is by disabling this extension.

**Comment by Solarinass** [comment]
Oh my goodness I am actually really sorry. It seems like I am looking at the wrong extension! I was using this extension https://extensions.gnome.org/extension/758/no-workspace-switcher-popup/ and this was the extension that was causing the problem! I installed your extension and it works great! Sorry for wasting your time.

**Comment by windsorschmidt** [comment]
Closing this due to (my) inactivity.
