### ISSUE TITLE
Support for GNOME 40 

### ISSUE THREAD

**Issue by yashrathi-git** [windsorschmidt/disable-workspace-switcher-popup#38]
This extension is not compatible with GNOME 40 on Fedora 34. Any plans for adding support for GNOME 40?

**Comment by windsorschmidt** [comment]
Hi. Issue #37 saw a PR merged from another user indicating support in GNOME 40. I have limited ability to test this plugin currently. Please try with the latest version (from about 18 days ago). Thanks.

**Comment by yashrathi-git** [comment]
I have tested, this extension on my main machine.
GNOME 40 (Fedora 34)
It works perfectly on my machine,
Thank You

**Comment by windsorschmidt** [comment]
👍🏼

**Comment by frotnir** [comment]
I'm having the same issue as @feimosi. The version of the extension seems to be outdated on https://extensions.gnome.org/extension/959/disable-workspace-switcher-popup/

**Comment by yashrathi-git** [comment]
@feimosi @frotnir yes it seems the version have not been released on gnome-extension. you could install the latest version directly from github, [see the from command-line section here](https://github.com/windsorschmidt/disable-workspace-switcher-popup#installation)

there is also another extension [Just Perfection](https://extensions.gnome.org/extension/3843/just-perfection/) that's up-to-date on gnome-extensions and supports gnome 40 and it have feature to disable workspace switcher overlay.

**Comment by yashrathi-git** [comment]
@feimosi @frotnir yes it seems the version have not been released on gnome-extension. you could install the latest version directly from github, [see the from command-line section here](https://github.com/windsorschmidt/disable-workspace-switcher-popup#installation)
