### ISSUE TITLE
Request for commit (push) access.

### ISSUE THREAD

**Issue by kfogel** [windsorschmidt/disable-workspace-switcher-popup#48]
Hi, @windsorschmidt.  If you'd be willing to give me push access to this repository, that would enable me to merge routine GNOME Shell version number updates directly.

The advantage for the project would be slightly faster updates.  The advantage for you would be less work :-).   The advantage for me would be reduced branch-management overhead across my various machines -- currently, when I `dist-upgrade` them, I often have to set them to temporarily track my latest gnome upgrade branch instead of your upstream `master` branch, until upstream catches up with whatever version of `gnome-shell` arrived in the upgrade.  This means I'm constantly switching branches, which just adds some overhead to my OS upgrade process.

If you'd prefer not to, that's fine; I'm happy to continue submitting PRs and waiting for them to be merged too.

**Comment by windsorschmidt** [comment]
Sounds great! Collaboration invite sent. 🧑🏼‍🤝‍🧑🏼🛠️

**Comment by kfogel** [comment]
Received & accepted.  Thanks!  Looking forward to helping the extension stay on top of gnome-shell updates.
